Feature/principle of least surprise
christopherwharrop/rocoto pull request #31
Opened 2018-12-19 15:48 UTC by samtrahan

Makes `-a`, `-c`, `-t`, and `-m` options consistent across all Rocoto commands.  This required refactoring the option parsing and task/cycle selection code.  Manpages added for rocotorewind and rocotocomplete.  Other manpages are updated to reflect new option parsing.

2018-12-19 17:01 UTC, christopherwharrop commented
This is a huge amount of changes.  It will take me a while to go thru this and evaluate it.

2018-12-19 17:06 UTC, samtrahan commented
Let me know if you want to do something over the phone or Hangouts.  It may go faster if I explain things.

2018-12-19 17:10 UTC, christopherwharrop commented
Since this is not related to the Slurm updates, let's leave it until after the holidays when I'm not being rushed to get so many things done.  After the other PRs are merged, you can merge develop onto this branch and continue to test and use it with all the other updates included.  I may give you a call next month to help get through it.

2018-12-19 17:13 UTC, samtrahan commented
This branch is already tested on top of the other PRs.  It was tested on top of them in the slurm-of-least-surprise branch.  That branch should match the final "develop" other than the one "if" statement about `<memory>`.

2018-12-19 17:14 UTC, christopherwharrop commented
Ok.  But, due to the huge number of changes involved, I want to spend some time looking at them before this gets merged.  I don't have that kind of time until next month.

2018-12-19 17:16 UTC, samtrahan commented
That's fine.  I'll update feature/principle-of-least-surprise and have people keep test it.  It is the version used by NEMS and the FV3 GFS workflows, so there will be plenty of testing.

2018-12-19 17:18 UTC, christopherwharrop commented
Great!  I'm happy to hear about the testing.  Even though the test is showing positive results, I still need to understand what's going on with the code before merging it.  Thank you for your patience.

2019-02-01 20:30 UTC, aerorahul reviewed
Dear Developers,

Sorry to intrude on this pull request.
I am trying to use Rocoto on a NASA cluster Discover with Slurm scheduler, and I could not get develop to work, so I used this branch and it works except for the following syntax error.

I had to change line 282 in slurmbatchsystem.rb to:
queued_jobs = queued_jobs.encode('UTF-8', 'binary', {:invalid => :replace, :undef => :replace, :        replace => ''})

This was basically what is in develop, without the conditional if encode check.

Thanks for your attention.

2019-02-04 15:23 UTC, christopherwharrop commented
@aerorahul, thanks for the note about that.  There has been some confusion about that line of code and the issue has to do with a Ruby 1.8.7 vs 2.x version compatibility conflict.  I thought I had it sorted out, but I'll take another look at it.  Which version of Ruby are you using on Discover?  The old "if" statement won't work because the offending code won't even parse in 1.8.7, so it's not just a question of checking the version and doing one thing or the other.

2019-02-04 15:29 UTC, aerorahul commented
@christopherwharrop 

`1003 discover35 ~ $ ruby --version`
`ruby 1.8.7 (2011-12-28 patchlevel 357) [x86_64-linux]`

Unfortunately, discover is so far behind in its operating system state, that I had to comment out that line completely in order to get it to work. Otherwise, I get `STATUS` as `UNAVAILABLE` regardless of what `scontrol show job` says.

I have to add, I am no expert in `SLURM`, `ruby` OR `rocoto`, and am simply reacting to issues on Discover.

After that fix, I was able to submit, monitor, rewind and resubmit jobs on Discover.

Please let me know if I could be of any help, since I do wish to have Rocoto usable on Discover.

Thanks.

2019-02-04 15:36 UTC, christopherwharrop commented
@aerorahul, Ok.  I suspected you were using 1.8.7.  We need to figure out what is going on.  I do have access to Ruby 1.8.7 on Jet and Theia (I can install it myself if needed) and so should be able to debug there.  But, as a precaution, I will probably ask you to try versions on Discover.  The reason for that line, and why I don't want to just get rid of it, is because it is necessary in order to correctly parse SLURM output on machines in other countries where there are unexpected characters.

You are correct, though, that this branch has the wrong version of that line and that it needs, at a minimum, to be corrected to the version that is now in develop.  As it is, this branch won't even parse on Ruby 1.8.7.

2019-02-04 15:37 UTC, christopherwharrop requested changes
Please merge develop onto this branch.  There are some things, like the encoding fix in slurmbatchsystem that are not here that should be here.

2019-02-04 16:51 UTC, christopherwharrop requested changes

2019-02-04 16:51 UTC, christopherwharrop commented on lib/wfmstat/statusengine.rb
> +
Please remove extra blank lines that do not add clarity.

2019-02-04 16:51 UTC, christopherwharrop commented on lib/wfmstat/statusengine.rb
> -        unless @options.tasks.nil?
Please delete the commented out lines and the extra blank line.

2019-02-04 16:51 UTC, christopherwharrop commented on lib/wfmstat/statusengine.rb
> -          unless @options.tasks.nil?
Please delete commented out lines.

2019-02-04 16:51 UTC, christopherwharrop commented on lib/wfmstat/statusengine.rb
> +              #puts "#{task}: not selected"
Please delete commented out line

2019-02-04 16:51 UTC, christopherwharrop commented on lib/workflowmgr/cycle.rb
> +
One too many blank lines.

2019-02-04 16:51 UTC, christopherwharrop commented on lib/wfmstat/wfmstatoption.rb
>    # Class StatusOption
Change comment to match class name

2019-02-04 16:51 UTC, christopherwharrop commented on lib/wfmstat/wfmstatoption.rb
>    end  # Class StatusOption
Change comment to match class name

2019-02-04 16:51 UTC, christopherwharrop commented on lib/workflowmgr/cycle.rb
> +    end  # active?
Change comment to match method name

2019-02-04 16:51 UTC, christopherwharrop commented on lib/workflowmgr/cycle.rb
> +    end  # activate!
Change comment to match method name

2019-02-04 16:51 UTC, christopherwharrop commented on lib/workflowmgr/selectionutil.rb
> +
One too many blank lines

2019-02-04 16:51 UTC, christopherwharrop commented on lib/workflowmgr/workflowdoc.rb
> -
Please don't remove blank lines unless you have a reason.

2019-02-04 16:51 UTC, christopherwharrop commented on lib/workflowmgr/workflowengine.rb
> +
One too many blank lines

2019-02-04 16:51 UTC, christopherwharrop commented on lib/workflowmgr/workflowengine.rb
> +          #puts "ACTIVE JOBS: <#{@active_jobs.keys.join('><')}>"
Remove commented line

2019-02-04 16:51 UTC, christopherwharrop commented on lib/workflowmgr/workflowengine.rb
> +            #puts "#{strcyc}: #{task_name}: consider this task"
Remove commented line

2019-02-04 16:51 UTC, christopherwharrop commented on lib/workflowmgr/workflowengine.rb
> +              #puts "#{strcyc}: #{task_name}: job has not been tried yet.  Doing nothing to this task."
Remove commented line

2019-02-04 16:51 UTC, christopherwharrop commented on lib/workflowmgr/workflowengine.rb
> +            #puts "#{strcyc}: #{task_name}: jobs exist for <#{cycjob.keys.join(', ')}>"
Remove commented line

2019-02-04 16:51 UTC, christopherwharrop commented on lib/workflowmgr/workflowengine.rb
> +              #puts "#{strcyc}: #{task_name}: job has not been tried yet for cycle #{strcyc}.  Doing nothing to this task."
Remove commented line

2019-02-04 16:51 UTC, christopherwharrop commented on lib/workflowmgr/workflowengine.rb
> +            # @dbServer.update_cycles([rewind_cycle])
Remove commented line

2019-02-04 16:51 UTC, christopherwharrop commented on lib/workflowmgr/workflowengine.rb
> +
Blank lines should not have tabs in them

2019-02-04 16:51 UTC, christopherwharrop commented on lib/workflowmgr/workflowselection.rb
> +    # select_tasks
Change comment to match method name

2019-02-04 16:51 UTC, christopherwharrop commented on lib/workflowmgr/workflowsubsetoptions.rb
> +    # validate_args
Change comment to match method name

2019-02-04 16:51 UTC, christopherwharrop commented on sbin/rocotoboot.rb
> +opt=WorkflowMgr::WorkflowSubsetOptions.new(ARGV,'rocotorewind','rewind')
Replace "rewind" with "boot"

2019-02-05 16:43 UTC, samtrahan commented
All trailing whitespace in Rocoto Ruby code has been removed and indentation tabs are now spaces.  I've removed commented-out code from many places.  The "develop" branch has been merged into this feature branch.  So far as I know, this feature branch is up-to-date with all bug fixes and documentation updates to the feature.

2019-02-05 17:35 UTC, christopherwharrop approved these changes
Thank you for fixing all the whitespace issues.

2019-02-05 17:36 UTC, merged